### ISSUE TITLE
Uses wrong sensor on iPhone

### ISSUE THREAD

**Issue by RobertGary1** [Bagarre/Pi2D2#1]
This worked great on my laptop but when I ran it on the iPhone I noticed the attitude was totally different. It turns out its not using the Stratux device at all. Its using the internal iPhone accelerators. If you move the phone around it changes the attitude. :)

-Robert

**Comment by Bagarre** [comment]
I thought I took that code out. https://github.com/Bagarre/Pi2D2/blob/master/www/js/test.js#L102-L110

Was just there to exercise the UI before I was talking to Stratux. 
Thanks for looking.

**Comment by Bagarre** [comment]
Lines are commented out to avoid confusion.

**Comment by RobertGary1** [comment]
Yes, I found the same and made the same change locally. I should have updated the issue. 

-Robert
