### ISSUE TITLE
Rework gmeter

### ISSUE THREAD

**Issue by Bagarre** [Bagarre/Pi2D2#8]
Make gmeter a curved scale with 3 needles - max, min, current. 
Easier to read. 

Consider removing gmeter all together and replace with airspeed arcs on a rotating dial similar to compass to take up less room.

**Comment by tailwindflyer** [comment]
![image](https://cloud.githubusercontent.com/assets/16809279/12537394/d86b147a-c283-11e5-9624-349982e2a117.jpeg)
I think your idea to remove the g meter and enhance the airspeed display is a good one.  Please see attached example from an MGL Extreme.  This seems to be one of the clearest little displays out there for airspeed and altitude.  Positioning the speed and alt digital read outs centrally on the y axis uses more display area but makes it clearer IMO.  

G could be displayed as a simple digital readout...unless you are planning aeros.

Also, on your screenshots I noticed that the "fixed" attitude reference bars either side of the central dot rotated with the horizon.  I think this might be better to stay fixed horizontal...and so perhaps the line lengths could be shortened to de clutter.

Please take these suggestions merely as that.  You are doing an awesome job here and I really think this has the potential to be used in many applications out there.  

Cheers

Rich

**Comment by Bagarre** [comment]
I actually made one with speed tapes at first but IMO it’s just not useful on a 480x320 4” screen.
On larger screens, sure they work fine but it was too hard to get the data at a glance on a small screen.
That’s why I went with larger numbers in the upper corners. it allowed me to keep the horizon big enough to be meaningful AND have altitude and speed readable.

The stationary Yellow bars are also there to help easily identify straight and level while the arrow on top will tell you if you’re in a 10 or 15 degree bank..if you care. 

Here’s the latest rendition that hasn’t been pushed to the repo yet.
The VSI and GMeter are able to take up very little space and still convey decently.

Im playing around with CDI and glide slope without cluttering things too much. Glide Slope will also serve as an altitude deviation so you’ll either see the ’15,000’ altitude setting OR the VLOC indication.
Same with the GPS or VOR indications…on one or the other.

Trying to fit so much information into a tiny 4” screen and still be useful is a real challenge but that’s part of the experiment for me.

![pi2d2shot2](https://cloud.githubusercontent.com/assets/347181/12538470/2b972020-c2a8-11e5-80bb-79fbf9c79ecb.png)

**Comment by tailwindflyer** [comment]
Good point re the speed tapes and small screen.  For sure the airspeed digital readout on your display is very clear.  

I think that the two yellow bars either side of the central dot could be omitted for clarity.  Also it seems a little unconventional to have these parallel the horizon (rather than remain fixed).  

The gmeter,  VSI and CDI changes look impressive.  Looks like you have been busy!

Also the heading compass looks better IMO with the added digits and slightly different scaling you have adopted.

**Comment by tailwindflyer** [comment]
I also liked the new beefed up roll markings, and the de cluttered pitch scale in your latest version.  

Might be better to make the max and min G pointers in grey or something to make it clearer when reading actual G.  Also, what about moving the scale so 1g is central?  How easy is it for user selection of max man values for the scale?  +5 or 6 and -2g would fit most applications - but user control would be great.

Once again, this is great work

Cheers

Rich

**Comment by Bagarre** [comment]
The gmeter and VSI are currently configurable but not separate max and min values.
https://github.com/Bagarre/Pi2D2/blob/master/www/js/Pi2D2.js#L14-L15
I should break configs and settings out to a separate file.

Moving 1G to centerline wouldnt be that much trouble.

I also thought about moving the dials vs moving the needles on both gmeter and VSI decided it wouldn't be better. Needle deflection on a scale is obvious at a glance while centerline numbers need to be read.

**Comment by tailwindflyer** [comment]
Ok thanks.  Don't worry about moving the 1g line as it would probably look worse with the fixed max/min range.  It is fine as is.  

I agree with your point about the moving dials being less easy to read at a glance than the needle.

**Comment by Bagarre** [comment]
lol. already made the change to the Gmeter. adjusted the spreads so it shows 1 more positive than negative.
So, with maxload=4 you get +4 -3 which is fine.

pushed to master so the changes are up. Even updated the screen shots.

https://github.com/Bagarre/Pi2D2/blob/master/screenshots/Pi2D2Shot2.png

**Comment by tailwindflyer** [comment]
That's good.  Like it.  
But shouldn't the yellow bars be fixed relative to be yellow "L" shapes?

Anyway, I think I will reclone from this latest build for my fork.

Thanks

**Comment by tailwindflyer** [comment]
Just looking at the last screenshot in a bit more detail I think that there are some issues with the pitch ladder presentation as well as the yellow reference bars.  On most PFDs the ladder is referenced from the horizon, while the central dot (and reference marks like the yellow bars) stay fixed to the aircraft datum.  

So in a 10 deg deck angle climb the central dot would be over the plus 10 deg ladder line.  If there was any bank applied, them the dot would be in the same place but the yellow (in this case) bars would be still fixed parallel to the wings (rather than the horizon).

Just my observations.  Let me know if you want to start this as a separate issue or not.  It may be per design for this setup.

Regards

Rich

**Comment by Bagarre** [comment]
You're right on the pitch ladder. I've been staring at that for a month, trying to figure out why it doesn't look right.
So, it's come full circle (pun) to where the yellow bar is fixed to the aircraft while the back card (Earth, Sky, Pitch Ladder and Bank Indicator) is fixed to the horizon outside.

![image](https://cloud.githubusercontent.com/assets/347181/12571692/99e1800c-c3b1-11e5-96bc-210796f0f251.png)

**Comment by tailwindflyer** [comment]
I think you almost have it nailed.  

Suggestions for what it's worth:
- drop the central white dot in the pitch ladder and revert to the white line separating the brown and blue?
- possibly revert the bank indicator triangle to white?  Also I am not sure if it looks neater on the outside of the scale like previously??
- perhaps make the max and min G value circle dots grey or something?

It is looking good though.

**Comment by Bagarre** [comment]
![pi2d2](https://cloud.githubusercontent.com/assets/347181/12591534/35c50d20-c436-11e5-9613-5be2a57afc44.png)
Latest run. 
1. I like the center white dot as it traps nicely in the cage when centered. I think it's a nice visual for now.
2. Im on the fence about the outer yellow marks but they do help show level flight easier and most gauges have them.
3. I made the G dots smaller. I think white is still correct as all other indicators are white.
4. The top roll marker is yellow because it's stationary like the 'airplane' in the middle. This is pretty common on steam gauge attitude indicators. Also, the top roll markers move with the horizon the same as a steam attitude indicator so the yellow pointer is always up and points to current roll.
5. I finally figured out how to clip the pitch ladder as it goes up and down!  it's a crazy combination of svg groups but it works and keeps the screen uncluttered.

**Comment by tailwindflyer** [comment]
Now that looks great.
- Agreed re the centre dot.  Looks very clear now you have reinstated the white horizon line.
- Gmeter circles look much better at that size.  Makes sense re your white colour convention.
- yellow roll markers look great in this version.  I really like the way you have incorporated the roll display this time.  My only slight issue is that Inpersonally preferred the tick mark at 45deg versus the new circle...but that is trivial.
- the pitch ladder clipping is awesome, neat job.

When you upload this I will put it through its paces with the test script and let you know if I see any other things you might want to play with.  IMO this is now far superior to the D2 display!

Cheers

Rich

**Comment by Bagarre** [comment]
https://github.com/Bagarre/Pi2D2/commit/36fd7d07c6dbbcefdd9d07eabddd15fda9e6ac42

G Meter done

**Comment by tailwindflyer** [comment]
That looks great.  

Nice job masking the Airspeed bar behind the G meter.  

It is looking very slick now.
